version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: 
          working_directory: ~/project/js
          command: yarn 
      - run: 
          working_directory: ~/project/js
          command: yarn test:ci
      